app_name: 'My App'
app_version: 1.0.0
db_name: mydb
db_host: localhost
db_port: 3306
db_driver: mysql
db_username: myusername
db_passwdd: mypasswd
ldap_host: localhost
ldap_username: myldapusername
ldap_passwd: myldappasswd
imap_host: imap.gmail.com
imap_port: '993'
